version: '3.8'

services:
  web:
    build: .
    container_name: moodle_custom_app
    restart: always
    ports:
      - "8110:80"
    environment:
      - MOODLE_URL=${MOODLE_URL}
      - MOODLE_DB_HOST=db
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodleuser
      - MOODLE_DB_PASSWORD=passwordRootMoodle
      - MOODLE_SITE_FULLNAME=${MOODLE_SITE_FULLNAME}
      - MOODLE_SITE_SHORTNAME=${MOODLE_SITE_SHORTNAME}
      - MOODLE_ADMIN_USER=${MOODLE_ADMIN_USER}
      - MOODLE_ADMIN_PASSWORD=${MOODLE_ADMIN_PASSWORD}
      - MOODLE_ADMIN_EMAIL=${MOODLE_ADMIN_EMAIL}
    volumes:
      - moodledata_vol:/var/www/moodledata
    depends_on:
      - db
    networks:
      - moodle_net
      - proxy_network

  db:
    image: mariadb:10.11
    container_name: moodle_custom_db
    restart: always
    environment:
      - MARIADB_DATABASE=moodle
      - MARIADB_USER=moodleuser
      - MARIADB_PASSWORD=passwordRootMoodle
      - MARIADB_ROOT_PASSWORD=passwordRootMoodle
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - moodle_net

  backup:
    image: offen/docker-volume-backup:latest
    container_name: moodle_backup
    restart: always
    depends_on:
      - db
      - web
    environment:
      # Credenciales AWS S3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      # Variables necesarias para el script de dump (FALTABAN AQUÍ)
      - MOODLE_DB_USER=moodleuser
      - MOODLE_DB_PASSWORD=passwordRootMoodle
      - MOODLE_DB_NAME=moodle
      # Configuración Backup
      - BACKUP_CRON_EXPRESSION=0 3 * * *
      - BACKUP_FILENAME=backup-moodle-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_RETENTION_DAYS=7
      - BACKUP_PRERUN_SCRIPT=apk add --no-cache mariadb-client && mysqldump -h db -u $MOODLE_DB_USER -p$MOODLE_DB_PASSWORD $MOODLE_DB_NAME > /backup/source/db_dump.sql
    volumes:
      - moodledata_vol:/backup/source/moodledata:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - moodle_net

volumes:
  moodledata_vol:
  db_data:

networks:
  proxy_network:
    external: true
  moodle_net: